apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  namespace: devops-bank

spec:
  replicas: 1
  selector:
    matchLabels:
      app: db      #Find pod with this label
  
  template:
    metadata:
      labels:
        app: db   #pods get this label
  
    spec:
      containers:
        - name: db
          image: postgres:15-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: devops-bank-config
                  key: DB_NAME

            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: devops-bank-secret
                  key: DB_USER
            
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: devops-bank-secret
                  key: DB_PASSWORD

          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data   # where to mount inside container
              subPath: postgres
              
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"

      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc
