apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: devops-bank

spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp2    # ← add this for EKS
  resources:
    requests:
      storage: 1Gi