apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: devops-bank

spec:
  type: ClusterIP
  selector:
    app: db     #Route traffic to pods with this label
  ports:
    - port: 5432  #Service port
      targetPort: 5432  #continer port