apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: devops-bank

spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  
  template:
    metadata:
      labels:
        app: frontend

    spec:
      containers:
        - name: frontend
          image: manish12588/devops-bank-app-frontend:72da664b5ad9c267d2fe04a304b54d44d8416e28
          ports:
            - containerPort: 80

          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "200m"

          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10
          
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5