apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devops-bank-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: default

  source:
    repoURL: https://github.com/Manish12588/DevOps-Bank-App.git
    targetRevision: main
    path: k8s
    directory:
      recurse: true        
    
  destination:
    server: https://kubernetes.default.svc
    namespace: devops-bank

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m